name: Pull Request Alerts

on:
  pull_request_target:
    types:
      - opened
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.actor, '[bot]') && github.event.pull_request.base.ref == 'master' }}
    steps:
      - name: Pull Request Alerts
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.pull_request.html_url || github.event.head_commit.url }} By ${{ github.actor }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
