name: Pull Request Alerts

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - reopened
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.actor, '[bot]') && github.event.pull_request.base.ref == 'master' && github.event.pull_request.draft == false }}
    steps:
      - name: Post a message in a channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: 'https://hooks.slack.com/services/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'
          webhook-type: incoming-webhook
          payload: |
            text: "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ github.event.pull_request.html_url || github.event.head_commit.url }} is ${{ github.event.action }} by ${{ github.actor }}"
